#Properties file for PropEditorX
Bundle-Vendor.0 = Santa Soft
Bundle-Name.0 = PropEditorX

propertiesEditorPreferencePageName=PropEditorX
editorPreferencePageName=Editor
checkDuplicationPreferencePageName=Duplication key
toggleCommentActionLabel=Togg&le Comment
expandAllActionLabel=E&xpand All
collapseAllActionLabel=C&ollapse All
showUnicodeEscActionLabel=Show Un&icode
contextLabel=PropEditorX
contextDescription=PropEditorX Scope
commandCategory=PropEditorX
toggleCommentCommandLabel=Toggle Comment
collapseAllCommandLabel=Collapse All
expandAllCommandLabel=Expand All
showUnicodeEscCommandLabel=Show Unicode
duplicationMarkerLabel=Property Duplication Problem
wizardName=Properties File
hoverLabel=Property
hoverDescription=Show properties.
proposalName=Property Proposals

